/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpskillingRouteImport } from './routes/upskilling'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ServiceProvidersRouteImport } from './routes/service-providers'
import { Route as RisingInvestorsRouteImport } from './routes/rising-investors'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as IndexRouteImport } from './routes/index'

const UpskillingRoute = UpskillingRouteImport.update({
  id: '/upskilling',
  path: '/upskilling',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceProvidersRoute = ServiceProvidersRouteImport.update({
  id: '/service-providers',
  path: '/service-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RisingInvestorsRoute = RisingInvestorsRouteImport.update({
  id: '/rising-investors',
  path: '/rising-investors',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/rising-investors': typeof RisingInvestorsRoute
  '/service-providers': typeof ServiceProvidersRoute
  '/students': typeof StudentsRoute
  '/upskilling': typeof UpskillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/rising-investors': typeof RisingInvestorsRoute
  '/service-providers': typeof ServiceProvidersRoute
  '/students': typeof StudentsRoute
  '/upskilling': typeof UpskillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/founders': typeof FoundersRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/rising-investors': typeof RisingInvestorsRoute
  '/service-providers': typeof ServiceProvidersRoute
  '/students': typeof StudentsRoute
  '/upskilling': typeof UpskillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/founders'
    | '/investors'
    | '/login'
    | '/partners'
    | '/rising-investors'
    | '/service-providers'
    | '/students'
    | '/upskilling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founders'
    | '/investors'
    | '/login'
    | '/partners'
    | '/rising-investors'
    | '/service-providers'
    | '/students'
    | '/upskilling'
  id:
    | '__root__'
    | '/'
    | '/founders'
    | '/investors'
    | '/login'
    | '/partners'
    | '/rising-investors'
    | '/service-providers'
    | '/students'
    | '/upskilling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoundersRoute: typeof FoundersRoute
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  RisingInvestorsRoute: typeof RisingInvestorsRoute
  ServiceProvidersRoute: typeof ServiceProvidersRoute
  StudentsRoute: typeof StudentsRoute
  UpskillingRoute: typeof UpskillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upskilling': {
      id: '/upskilling'
      path: '/upskilling'
      fullPath: '/upskilling'
      preLoaderRoute: typeof UpskillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-providers': {
      id: '/service-providers'
      path: '/service-providers'
      fullPath: '/service-providers'
      preLoaderRoute: typeof ServiceProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rising-investors': {
      id: '/rising-investors'
      path: '/rising-investors'
      fullPath: '/rising-investors'
      preLoaderRoute: typeof RisingInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoundersRoute: FoundersRoute,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  RisingInvestorsRoute: RisingInvestorsRoute,
  ServiceProvidersRoute: ServiceProvidersRoute,
  StudentsRoute: StudentsRoute,
  UpskillingRoute: UpskillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
